name: Deploy

on:
  push:
    branches:
    - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  STACK_NAME: next-ts-amplify-hosting-stack
  APP_NAME: AmplifyApp

jobs:
  deploy:
    strategy:
      matrix:
        node-version: [22.x]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: |
          - recursive: true
            args: [--no-frozen-lockfile]
          - args: [--global, aws-cdk]

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.OIDC_IAM_ROLE }}
        role-session-name: GitHubActions
        aws-region: us-west-2

    - name: Build
      run: pnpm build

    - name: Deploy
      working-directory: cdk
      run: cdk deploy -c stack_name=${{ env.STACK_NAME }} -c app_name=${{ env.APP_NAME }}
