name: Deploy

on:
  push:
    branches:
    - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  STACK_NAME: next-ts-amplify-hosting-stack
  APP_NAME: AmplifyApp

jobs:
  deploy:
    strategy:
      matrix:
        node-version: [18.x]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 8.6.1
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.6.0
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
        cache: pnpm

    - name: Build
      run: pnpm build

    - name: Install cdk
      run: |
        npm i -g aws-cdk

    - name: Deploy
      working-directory: cdk
      run: cdk deploy -c stack_name=${{ env.STACK_NAME }} -c app_name=${{ env.APP_NAME }}
